"""
providers/mock.py — Credential-free deterministic executor (§2, §15/P2).

Used for all testing until P9. Always healthy; streams a realistic event
sequence so the orchestrator, router, and WS pipeline are all exercisable
without any real provider credentials.

Simulates:
  log → phase(planning) → phase(running) → token(×N) → result
"""
from __future__ import annotations

import asyncio
import os
from collections.abc import AsyncIterator
from typing import Any

from app.providers.base import (
    EventKind,
    ExecEvent,
    ExecResult,
    Executor,
    Usage,
)

_MOCK_REPORT = """\
# Mock Research Report

## Executive Summary
This is a deterministic mock response generated by the batonkeep mock provider.
No real inference was performed; this output is used for pipeline verification.

## Findings
- The mock executor streams events in the correct sequence.
- The orchestrator, router, and WebSocket pipeline are all exercisable offline.
- Token counts and cost are simulated (100 in / 200 out / $0.000).

## Conclusion
Replace the `mock` candidate with `claude`, `grok`, or `agy` after running `make auth`.

*Source: batonkeep mock provider v0.1*
"""

_MOCK_JSON = '{"status": "mock", "report_type": "mock", "confidence": 1.0}'


class MockExecutor(Executor):
    """Deterministic, credential-free backend for pipeline testing."""

    name: str = "mock"
    tier: str = "mock"

    def __init__(
        self,
        name: str = "mock",
        *,
        latency_ms: int = 50,
        token_chunks: int = 5,
        simulate_rate_limit: bool = False,
    ) -> None:
        self.name = name
        self.tier = "mock"
        self._latency_ms = latency_ms
        self._token_chunks = token_chunks
        self._simulate_rate_limit = simulate_rate_limit

    @property
    def kind(self) -> str:
        return "mock"

    def is_healthy(self) -> bool:
        return not self._simulate_rate_limit

    async def run_stream(
        self,
        prompt: str,
        *,
        workdir: str,
        tools_enabled: bool = True,
        max_rounds: int = 10,
        budget_usd: float = 1.0,
        extra: dict[str, Any] | None = None,
    ) -> AsyncIterator[ExecEvent]:
        delay = self._latency_ms / 1000

        yield ExecEvent(kind=EventKind.log, message=f"[mock] received prompt ({len(prompt)} chars)")
        await asyncio.sleep(delay)

        yield ExecEvent(kind=EventKind.phase, phase="planning", message="[mock] planning")
        await asyncio.sleep(delay)

        if self._simulate_rate_limit:
            yield ExecEvent(
                kind=EventKind.error,
                message="rate_limit_reached: mock limit exceeded; resets in 5s",
                data={"rate_limit": True, "reset_after_seconds": 5},
            )
            return

        yield ExecEvent(kind=EventKind.phase, phase="running", message="[mock] running")
        await asyncio.sleep(delay)

        # Build-session mode (M1.1): act like a coding agent and actually edit a
        # file in the workspace so the per-turn change is real and inspectable.
        if extra and extra.get("session"):
            seq = extra.get("turn_seq", 0)
            user_message = (extra.get("user_message") or prompt)[:120].strip()
            try:
                index_path = os.path.join(workdir, "index.html")
                with open(index_path, "a", encoding="utf-8") as f:
                    f.write(f"<!-- mock turn {seq}: {user_message} -->\n")
                yield ExecEvent(
                    kind=EventKind.tool,
                    message=f"[mock] wrote index.html (turn {seq})",
                    data={"tool": "file_write", "path": "index.html"},
                )
            except OSError:
                pass

        # Stream the mock report in chunks
        report = _MOCK_REPORT
        chunk_size = max(1, len(report) // self._token_chunks)
        for i in range(0, len(report), chunk_size):
            chunk = report[i : i + chunk_size]
            yield ExecEvent(kind=EventKind.token, text=chunk, message="")
            await asyncio.sleep(delay / self._token_chunks)

        usage = Usage(tokens_in=100, tokens_out=200, cost_usd=0.0)
        result = ExecResult(
            text=report,
            usage=usage,
            provider=self.name,
            model="mock-v1",
        )

        yield ExecEvent(
            kind=EventKind.result,
            message="[mock] completed",
            data={"result": result, "usage": usage.__dict__},
        )
